#!/bin/bash
export ONDERZEEER_GO_DIR="$(pwd)/.go"

export PATH="$ONDERZEEER_GO_DIR/toolchain/bin:$PATH"
export GOPATH="$ONDERZEEER_GO_DIR/gopath"
export GOMODCACHE="$ONDERZEEER_GO_DIR/modcache"
export GOCACHE="$ONDERZEEER_GO_DIR/buildcache"
